console.group("Level 1");
console.log("Part of level 1");
console.log("Part of level 1");
console.log("Part of level 1");
console.group("Level 2");
console.log("Part of level 2");
console.log("Part of level 2");
console.groupEnd("Level 2");
console.group("Level 3");
console.log("Part of 3");
console.group("Level 4");
console.log("Part of  4");
console.groupEnd("Level 4");
console.groupEnd("Level 3");
console.groupEnd("Level 1");
